"""
main.py — FastAPI app entry point.

This is the file you run: `uvicorn main:app --reload`

What's here:
  1. App creation with lifespan (startup/shutdown hooks)
  2. CORS middleware — allows your Next.js frontend to call this API
  3. Router registration — connects all the routers to the app
  4. Health check endpoint — to verify the server is alive
  5. Global exception handler — clean error responses

HOW FASTAPI WORKS (quick mental model):
  - You define routes with decorators: @router.get("/path")
  - FastAPI reads your function's type hints to auto-validate input/output
  - Pydantic schemas handle all the validation
  - `Depends()` is dependency injection — like middleware but per-route
  - On startup, Python loads this file, creates the `app` object,
    uvicorn starts serving HTTP requests to it

RUN COMMANDS:
  Development (auto-reload on file save):
    uvicorn main:app --reload --port 8000

  Production:
    uvicorn main:app --host 0.0.0.0 --port 8000 --workers 4

API DOCS (auto-generated by FastAPI — no extra work needed):
  http://localhost:8000/docs    ← Swagger UI (interactive)
  http://localhost:8000/redoc  ← ReDoc (cleaner reading)
"""

from contextlib import asynccontextmanager
from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse

from config import settings
from database import warm_lookup_cache
from routers import questions, tests, auth as auth_router, courses as courses_router
from routers.analysis import router as analysis_router   # Phase 5
from routers.chatbot import router as chatbot_router
from routers.payments import router as payments_router
from routers.exams import router as exams_router
from routers.resources import router as resources_router



# ── Lifespan: startup + shutdown hooks ────────────────────────────────────────
# This replaces the old @app.on_event("startup") pattern
# Code before `yield` runs at startup, after `yield` runs at shutdown

@asynccontextmanager
async def lifespan(app: FastAPI):
    # ── STARTUP ──────────────────────────────────────────────────────────
    print("GATER Backend starting...")
    warm_lookup_cache()           # Load subjects/topics/branches into memory
    print("Startup complete. Ready to serve requests.")

    yield  # <-- app is running here

    # ── SHUTDOWN ─────────────────────────────────────────────────────────
    print("GATER Backend shutting down...")


# ── App creation ───────────────────────────────────────────────────────────────

app = FastAPI(
    title        = "GATER API",
    description  = "Backend for the GATE Custom Test Platform",
    version      = "1.0.0",
    docs_url     = "/docs",       # Swagger UI
    redoc_url    = "/redoc",      # ReDoc
    lifespan     = lifespan,
)


# ── CORS Middleware ────────────────────────────────────────────────────────────
# Without this, your Next.js frontend (localhost:3000) can't call this API.
# The browser blocks cross-origin requests unless the server explicitly allows them.
# In production, replace localhost URLs with your actual Vercel domain.

app.add_middleware(
    CORSMiddleware,
    allow_origins     = settings.allowed_origins,
    allow_credentials = True,
    allow_methods     = ["*"],    # GET, POST, PUT, DELETE, OPTIONS
    allow_headers     = ["*"],    # Authorization, Content-Type, etc.
)


# ── Global exception handler ───────────────────────────────────────────────────
# Catches any unhandled Python exception and returns a clean JSON error
# instead of a 500 HTML page (which the frontend can't parse).

@app.exception_handler(Exception)
async def global_exception_handler(request: Request, exc: Exception):
    # In production, log this to Sentry instead of printing
    print(f"[ERROR] Unhandled exception on {request.url}: {exc}")
    return JSONResponse(
        status_code=500,
        content={"detail": "Internal server error. Please try again."},
    )


# ── Register routers ───────────────────────────────────────────────────────────
# Each router has its own prefix defined in the router file.
# Registering here attaches those routes to the main app.

app.include_router(questions.router)   # /questions, /questions/subjects, /questions/topics
app.include_router(tests.router)       # /test, /test/{id}/submit, /test/{id}/result
app.include_router(analysis_router)    # /analysis/{id}/generate, /analysis/{id}  ← Phase 5
app.include_router(chatbot_router) 
app.include_router(payments_router)   # payment routes
app.include_router(exams_router)      # /exams, /exams/{id}/branches, /exams/{id}/subjects
app.include_router(auth_router.router) # auth routes
app.include_router(courses_router.router)
app.include_router(resources_router)

# ── Health check ───────────────────────────────────────────────────────────────
# Simple endpoint to verify the server is alive.
# Used by: Render/Railway health checks, your own monitoring, frontend "is backend up?" check.

@app.get("/health", tags=["System"])
def health_check():
    return {
        "status":  "ok",
        "version": "1.0.0",
        "env":     settings.app_env,
    }


@app.get("/", tags=["System"])
def root():
    return {
        "message": "GATER API is running. Visit /docs for the API reference.",
        "docs":    "/docs",
    }
