"""
ingest_pdf_v2.py — Accurate GATE PYQ & non-PYQ ingestion

Fixes over v1:
  1. Diagrams/figures extracted via PyMuPDF → uploaded to Supabase Storage → image_url
  2. Math symbols normalized (σ→sigma, √→sqrt, ∂→partial …)
  3. Marks parsed from PDF section headers (not hardcoded ranges)
  4. PYQ answer key from separate PDF  (--answer-pdf gate_DA2025_answer.pdf)
  5. Non-PYQ answers generated by AI   (solve_and_tag_with_ai)
  6. Robust Q-number regex

Usage:
    # PYQ with answer key PDF
    python ingest_pdf_v2.py --pdf Gate_DA2025.pdf --year 2025 --answer-pdf gate_DA2025_answerkey.pdf --dry-run

    # Non-PYQ (AI solves the questions)
    python ingest_pdf_v2.py --pdf my_practice.pdf --year 2025 --no-pyq --dry-run

Dependencies:  pip install pymupdf pdfplumber groq supabase pydantic python-dotenv tqdm
"""

import re
import os
import sys
import csv
import time
import argparse
import unicodedata
import io

import pdfplumber
import fitz                    # PyMuPDF
from tqdm import tqdm
from core import (
    QuestionIn, QuestionType, Difficulty,
    tag_with_ai, solve_and_tag_with_ai,
    insert_question, upload_to_storage, make_text_block,
)


# ═══════════════════════════════════════════════════════════════════════════════
#  1. MATH UNICODE NORMALIZER
# ═══════════════════════════════════════════════════════════════════════════════

MATH_MAP = {
    # Greek lowercase
    "\u03b1": "alpha", "\u03b2": "beta",   "\u03b3": "gamma",
    "\u03b4": "delta", "\u03b5": "epsilon", "\u03b7": "eta",
    "\u03b8": "theta", "\u03bb": "lambda",  "\u03bc": "mu",
    "\u03c0": "pi",    "\u03c1": "rho",     "\u03c3": "sigma",
    "\u03c4": "tau",   "\u03c6": "phi",     "\u03c9": "omega",
    # Greek uppercase
    "\u0393": "Gamma", "\u0394": "Delta",   "\u0398": "Theta",
    "\u039b": "Lambda","\u03a3": "Sigma",   "\u03a6": "Phi",
    "\u03a9": "Omega",
    # Operators & relations
    "\u221a": "sqrt",  "\u221e": "inf",     "\u2202": "partial",
    "\u222b": "integral", "\u2211": "sum",  "\u220f": "product",
    "\u2248": "~=",    "\u2260": "!=",      "\u2264": "<=",
    "\u2265": ">=",    "\u00b1": "+/-",      "\u00d7": "*",
    "\u00f7": "/",     "\u00b2": "^2",       "\u00b3": "^3",
    # Arrows
    "\u2192": "->",    "\u2190": "<-",      "\u21d2": "=>",
    # Logic / sets
    "\u2208": " in ",  "\u2209": " not in ","\u2229": " ∩ ",
    "\u222a": " ∪ ",   "\u2282": " ⊂ ",     "\u00ac": "NOT ",
    "\u2227": " AND ", "\u2228": " OR ",
    "\u2200": "for all ", "\u2203": "exists ",
    "\u2286": " subseteq ", "\u2287": " supseteq ",
    # Dashes
    "\u2013": "-",     "\u2014": "-",
}


def clean_math_text(text: str) -> str:
    """Replace Unicode math symbols with readable ASCII equivalents."""
    if not text:
        return text
    text = text.replace("\uFFFD", " ")  # Unicode replacement char
    for char, repl in MATH_MAP.items():
        text = text.replace(char, repl)
    text = unicodedata.normalize("NFC", text)
    # Collapse noisy punctuation sequences produced by OCR/text extraction.
    text = re.sub(r"\?{2,}", "?", text)
    text = re.sub(r"[ \t]{2,}", " ", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


def extract_best_page_text(pdf_path: str) -> str:
    """
    Extract page text using both pdfplumber and PyMuPDF, and keep the better one.
    Heuristic: fewer unknown placeholders ('?' / replacement chars) wins.
    """
    all_pages: list[str] = []
    with pdfplumber.open(pdf_path) as pdf, fitz.open(pdf_path) as doc:
        for i, page in enumerate(pdf.pages):
            p_text = page.extract_text() or ""
            f_text = doc[i].get_text("text", sort=True) or ""

            # Count unknowns in RAW text (before cleaning)
            p_unknown = p_text.count("?") + p_text.count("\uFFFD")
            f_unknown = f_text.count("?") + f_text.count("\uFFFD")

            # Prefer lower unknown count; tie-break by longer non-whitespace content.
            # Prefer pdfplumber (p_text) on ties as it often handles character spacing better.
            choose_fitz = (f_unknown < p_unknown) or (
                f_unknown == p_unknown and len(f_text.replace(" ", "")) > len(p_text.replace(" ", ""))
            )
            raw_best = f_text if choose_fitz else p_text
            best = clean_math_text(raw_best)
            all_pages.append(best)
    return "\n".join(all_pages)


# ═══════════════════════════════════════════════════════════════════════════════
#  2. MARKS PARSER  — reads section headers from PDF text
# ═══════════════════════════════════════════════════════════════════════════════

def parse_marks_map(raw_text: str) -> dict[str, int]:
    """
    Parse section headers from the ACTUAL Gate DA 2025 PDF:
        'Q.1 – Q.5 Carry ONE mark Each'       (page 1)
        'Q.6 – Q.10 Carry TWO marks Each'     (page 5)
        'Q. 11 – Q. 35 carry one mark each.'   (page 10)
        'Q. 36 – Q. 65 carry two marks each.'  (page 17)
    Returns: {"1": 1, "2": 1, ..., "36": 2, ...}
    """
    marks_map: dict[str, int] = {}

    # Flexible pattern that handles:
    #   Q.1 – Q.5    (no space after dot)
    #   Q. 11 – Q. 35  (space after dot)
    #   Q.1 to Q.25    ("to" instead of dash)
    #   – or - or —     (various dash types)
    pattern = re.compile(
        r"Q\.\s*(\d{1,2})\s*"       # Q. start_num
        r"[–\-—]+\s*"               # dash (en-dash, hyphen, em-dash)
        r"Q\.\s*(\d{1,2})\s+"       # Q. end_num
        r".*?"                       # anything in between
        r"\b(one|two|1|2)\s*mark",  # one/two/1/2 mark
        re.IGNORECASE,
    )

    for m in pattern.finditer(raw_text):
        start = int(m.group(1))
        end   = int(m.group(2))
        word  = m.group(3).lower()
        val   = {"one": 1, "two": 2, "1": 1, "2": 2}.get(word, 1)
        for n in range(start, end + 1):
            marks_map[str(n)] = val

    if marks_map:
        return marks_map

    # Fallback: standard GATE structure (30×1mk + 35×2mk)
    print("  [INFO] Could not parse marks sections — using default GATE layout")
    for n in range(1, 36):
        marks_map[str(n)] = 1
    for n in range(36, 66):
        marks_map[str(n)] = 2
    return marks_map


# ═══════════════════════════════════════════════════════════════════════════════
#  3. ANSWER KEY PDF PARSER
# ═══════════════════════════════════════════════════════════════════════════════

def parse_answer_key_pdf(answer_pdf_path: str) -> dict[str, str | list[str]]:
    """
    Extract answers from a GATE answer key PDF.

    The real format (Gate_DA2025_answerkey.pdf) is a table:
        Q.No  Session  Q.Type  Section  Key/Range  Marks
        1     5        MCQ     GA       A          1
        24    5        MSQ     DA       A;B;C      1
        31    5        NAT     DA       0.25 to 0.25  1
        62    5        NAT     DA       MTA        2

    Handles:
        MCQ  →  "A"
        MSQ  →  ["A","B","C"]  (from "A;B;C")
        NAT  →  "0.25"          or range "0.285 to 0.287" → midpoint
        MTA  →  "MTA"           (Marks to All)
    """
    answer_key: dict[str, str | list[str]] = {}

    all_text = ""
    with pdfplumber.open(answer_pdf_path) as pdf:
        for page in pdf.pages:
            text = page.extract_text()
            if text:
                all_text += text + "\n"

    if not all_text.strip():
        print(f"  [ERROR] No text in answer key PDF: {answer_pdf_path}")
        return answer_key

    # Each data row: "N  5  TYPE  SECTION  KEY/RANGE  MARKS"
    # Pattern: start-of-line number, then session(5), type, section, then the KEY
    row_pattern = re.compile(
        r"^(\d{1,2})\s+"              # Q number
        r"\d+\s+"                      # Session (always 5, ignore)
        r"(MCQ|MSQ|NAT)\s+"            # Question type
        r"(?:GA|DA)\s+"                # Section (ignore)
        r"(.+?)\s+"                    # Key/Range (capture greedily up to marks)
        r"(\d)\s*$",                   # Marks (1 or 2)
        re.MULTILINE | re.IGNORECASE,
    )

    for m in row_pattern.finditer(all_text):
        q_num  = m.group(1)
        q_type = m.group(2).upper()
        raw    = m.group(3).strip()

        # MTA → Marks to All
        if raw.upper() == "MTA" or raw.lower().startswith("marks to"):
            answer_key[q_num] = "MTA"

        # MSQ → "A;B;C" → ["A", "B", "C"]
        elif q_type == "MSQ" and re.search(r"[A-D]", raw):
            answer_key[q_num] = [c.strip().upper() for c in re.split(r"[;,]", raw) if c.strip()]

        # NAT → "0.25 to 0.25" or "0.285 to 0.287" → midpoint
        elif q_type == "NAT":
            if "to" in raw.lower():
                parts = re.split(r"\s*to\s*", raw, flags=re.I)
                try:
                    lo, hi = float(parts[0]), float(parts[1])
                    answer_key[q_num] = str(round((lo + hi) / 2, 6))
                except (ValueError, IndexError):
                    answer_key[q_num] = raw
            else:
                answer_key[q_num] = raw

        # MCQ → single letter "A"
        elif q_type == "MCQ" and raw.upper() in ("A", "B", "C", "D"):
            answer_key[q_num] = raw.upper()

        # Fallback
        else:
            answer_key[q_num] = raw

    print(f"  Loaded {len(answer_key)} answers from answer key PDF")

    # Quick sanity check
    if answer_key:
        mcq = sum(1 for v in answer_key.values() if isinstance(v, str) and v in "ABCD")
        msq = sum(1 for v in answer_key.values() if isinstance(v, list))
        nat = sum(1 for v in answer_key.values() if isinstance(v, str) and re.match(r"[\d.]", v))
        mta = sum(1 for v in answer_key.values() if v == "MTA")
        print(f"    MCQ: {mcq}  |  MSQ: {msq}  |  NAT: {nat}  |  MTA: {mta}")

    return answer_key


# ═══════════════════════════════════════════════════════════════════════════════
#  4. IMAGE/FIGURE EXTRACTOR  — PyMuPDF
# ═══════════════════════════════════════════════════════════════════════════════

# Gate PDFs have recurring images on every/most pages:
#   - 2036x2037 JPEG  = watermark / background (on ALL 34 pages)
#   - 146x146   PNG   = GATE logo (on first ~9 pages)
# These must be filtered out. Only unique-sized images are real diagrams.

def _find_recurring_image_sizes(doc: fitz.Document, threshold: int = 5) -> set[tuple[int, int]]:
    """
    Scan all pages and find image sizes that appear on >= `threshold` pages.
    Those are watermarks / logos / repeated branding — not question diagrams.
    """
    size_count: dict[tuple[int, int], int] = {}
    for page in doc:
        seen_on_page: set[tuple[int, int]] = set()
        for img_info in page.get_images(full=True):
            try:
                base = doc.extract_image(img_info[0])
                size = (base["width"], base["height"])
                if size not in seen_on_page:
                    seen_on_page.add(size)
                    size_count[size] = size_count.get(size, 0) + 1
            except Exception:
                pass
    return {s for s, c in size_count.items() if c >= threshold}


def extract_images_from_pdf(pdf_path: str) -> dict[int, list[dict]]:
    """
    Extract embedded images from each page using PyMuPDF.
    Automatically filters out watermarks, logos, and branding images
    that appear on many pages (detected by recurring dimensions).

    Returns: {page_num: [{"bytes": b"...", "ext": "png", "rect": Rect, ...}, ...]}
    """
    page_images: dict[int, list[dict]] = {}
    doc = fitz.open(pdf_path)

    # First pass: identify recurring images (watermarks/logos)
    recurring = _find_recurring_image_sizes(doc, threshold=5)
    if recurring:
        print(f"    Filtered recurring images (watermark/logo): {recurring}")

    # Second pass: extract only real diagram images
    for page_num in range(len(doc)):
        page = doc[page_num]
        images_on_page = []

        for img_info in page.get_images(full=True):
            xref = img_info[0]
            try:
                base = doc.extract_image(xref)
                w, h = base["width"], base["height"]

                # Skip tiny images (bullets, decorations) based on area to allow wide/short diagrams
                if w * h < 4000:
                    continue

                # Skip recurring watermarks/logos
                if (w, h) in recurring:
                    continue

                # Get position of this image on the page
                rects = page.get_image_rects(xref)
                rect  = rects[0] if rects else None

                images_on_page.append({
                    "bytes": base["image"],
                    "ext":   base["ext"],
                    "width": w,
                    "height": h,
                    "rect":  rect,
                })
            except Exception as e:
                print(f"    [WARN] Image xref={xref} page {page_num+1}: {e}")

        if images_on_page:
            page_images[page_num + 1] = images_on_page

    doc.close()
    return page_images


def upload_question_image(
    fig: dict, year: int, branch: str, q_num: str, dry_run: bool
) -> str | None:
    """Upload a single figure to Supabase Storage and return the public URL."""
    if dry_run:
        return f"[DRY-RUN] would upload {year}/{branch}/Q{q_num}.{fig['ext']}"

    ext  = fig.get("ext", "png")
    path = f"{year}/{branch}/Q{q_num}_fig.{ext}"
    ctype = "image/png" if ext == "png" else "image/jpeg"
    return upload_to_storage(fig["bytes"], path, content_type=ctype)


# ═══════════════════════════════════════════════════════════════════════════════
#  5. QUESTION PARSER  — robust regex
# ═══════════════════════════════════════════════════════════════════════════════

def build_page_question_map(pdf_path: str) -> dict[int, list[str]]:
    """
    Find which question numbers START on each page.
    Scans the full text line by line per page for patterns like:
        Q.1, Q.11, Q. 11, Q11  (the real PDF uses all of these)
    Returns: {page_num: ["1", "2", ...]}
    """
    page_qnums: dict[int, list[str]] = {}
    # Pattern: "Q." optionally followed by space, then 1-2 digits
    # Must be followed by a word boundary to avoid matching range headers in some cases
    q_start = re.compile(r"Q\.\s*(\d{1,2})\b")

    with pdfplumber.open(pdf_path) as pdf:
        for page_num, page in enumerate(pdf.pages, start=1):
            text = page.extract_text() or ""
            found = []
            for line in text.split("\n"):
                # Skip section headers like "Q.1 – Q.5 Carry ONE mark"
                if re.search(r"carry|mark|each", line, re.I):
                    continue
                for m in q_start.finditer(line):
                    qn = m.group(1)
                    if qn not in found:
                        found.append(qn)
            if found:
                page_qnums[page_num] = found
    return page_qnums


def build_question_page_ranges(page_qnums: dict[int, list[str]], total_pages: int) -> dict[str, tuple[int, int]]:
    """
    Build question -> (start_page, end_page) map.
    A question continues until the page before the next question starts.
    """
    starts: list[tuple[str, int]] = []
    for page in sorted(page_qnums.keys()):
        for qn in page_qnums[page]:
            starts.append((qn, page))

    ranges: dict[str, tuple[int, int]] = {}
    for idx, (qn, start_page) in enumerate(starts):
        end_page = (starts[idx + 1][1] - 1) if idx + 1 < len(starts) else total_pages
        if end_page < start_page:
            end_page = start_page
        ranges[qn] = (start_page, end_page)
    return ranges


def extract_questions_from_text(raw_text: str) -> list[dict]:
    """
    Parse raw PDF text into structured question dicts.

    The real GATE DA 2025 PDF uses:
      - "Q.1 Courage : Bravery ..."          (Q dot number)
      - "Q.11 Suppose X and Y ..."           (Q dot number, no space)
      - "Q. 11 – Q. 35 carry one mark each"  (section header — must skip)

    Strategy: find all "Q.N" at the start of lines, then extract the text
    between consecutive Q-markers.
    """
    questions = []

    # Find all question start positions.
    # Pattern: line starts (after optional whitespace) with Q. followed by number
    # We use a more flexible boundary to handle cases where text starts immediately after Q.N
    q_positions = []  # list of (char_offset, q_number)
    for m in re.finditer(r"(?:^|\n)\s*Q\.\s*(\d{1,2})\b", raw_text):
        # Check the rest of the line — skip if it's a marks header
        line_end = raw_text.find("\n", m.end())
        if line_end == -1:
            line_end = len(raw_text)
        rest_of_line = raw_text[m.end():line_end]
        if re.search(r"carry|mark.*each|–\s*Q\.|to\s*Q\.", rest_of_line, re.I):
            continue  # This is a section header, not a question
        q_positions.append((m.start(), m.group(1)))

    # Extract question bodies between consecutive Q markers
    for idx, (pos, q_num) in enumerate(q_positions):
        # Body starts after "Q.N "
        body_start = raw_text.index(q_num, pos) + len(q_num)
        body_end = q_positions[idx + 1][0] if idx + 1 < len(q_positions) else len(raw_text)
        q_body = raw_text[body_start:body_end].strip()

        if not q_body or len(q_body) < 15:
            continue

        # Remove page footers like "Organizing Institute: IIT Roorkee Page X of 34"
        q_body = re.sub(r"Organizing Institute:.*?Page \d+ of \d+", "", q_body).strip()
        # Remove next-page header like "Data Science & Artificial Intelligence - DA"
        q_body = re.sub(r"Data Science.*?- DA", "", q_body).strip()
        # Remove GATE2025 header
        q_body = re.sub(r"GATE\s*2025.*?-\s*DA", "", q_body).strip()

        if len(q_body) < 15:
            continue

        # Detect MSQ
        is_msq = bool(re.search(r"one or more|select all|multiple.*correct", q_body, re.I))

        # Extract options (A) (B) (C) (D)
        opt_re = re.compile(r"\(([A-D])\)\s*(.*?)(?=\([A-D]\)|\Z)", re.DOTALL)
        opt_matches = opt_re.findall(q_body)

        if opt_matches:
            options = [clean_math_text(m[1].strip()) for m in opt_matches]
            q_type  = QuestionType.MSQ if is_msq else QuestionType.MCQ
            first_opt_pos = q_body.find(f"({opt_matches[0][0]})")
            q_text = q_body[:first_opt_pos].strip()
        else:
            options = None
            q_type  = QuestionType.NAT
            q_text  = q_body

        q_text = clean_math_text(re.sub(r"\s+", " ", q_text).strip())
        if len(q_text) < 15:
            continue

        questions.append({
            "number":        q_num,
            "text":          q_text,
            "options":       options,
            "question_type": q_type,
        })

    return questions


# ═══════════════════════════════════════════════════════════════════════════════
#  6. IMAGE ↔ QUESTION ASSOCIATION
# ═══════════════════════════════════════════════════════════════════════════════

def associate_images(
    questions: list[dict],
    page_images: dict[int, list[dict]],
    page_qnums: dict[int, list[str]],
    pdf_path: str,
) -> dict[str, dict]:
    """
    Map each question number to its associated figure (if any).
    Logic:
      - Image on page P → find which Q numbers start on page P
      - If Q text references figure/diagram/graph → assign image to that Q
      - Otherwise assign to first Q on the same page that has no image yet
    Returns: {q_num: fig_dict}
    """
    q_images: dict[str, dict] = {}
    assigned_images: set[int] = set()       # track used image ids

    # Build question page ranges (handles questions spanning multiple pages)
    max_page = max(page_images.keys()) if page_images else (max(page_qnums.keys()) if page_qnums else 1)
    q_ranges = build_question_page_ranges(page_qnums, max_page)

    # Questions that reference a figure
    fig_words = re.compile(r"\b(figure|diagram|graph|chart|image|plot|tree)\b", re.I)

    for q in questions:
        qn   = q["number"]
        q_start, q_end = q_ranges.get(qn, (None, None))
        if not q_start:
            continue

        candidate_pages = [p for p in range(q_start, q_end + 1) if p in page_images]
        if not candidate_pages:
            continue

        figs = []
        for p in candidate_pages:
            figs.extend([(p, idx, fig) for idx, fig in enumerate(page_images[p])])
        has_ref = bool(fig_words.search(q["text"]))

        if has_ref:
            assigned = False
            for page, idx, fig in figs:
                img_id = (page, idx)
                if img_id not in assigned_images:
                    q_images[qn] = fig
                    assigned_images.add(img_id)
                    assigned = True
                    break
            
            # --- Precise Vector Diagram Extraction (Fallback) ---
            # If the question references a figure but no embedded raster image was found,
            # isolate the vector graphics (lines, rects, curves) within the question bounds.
            if not assigned:
                try:
                    with pdfplumber.open(pdf_path) as pdf:
                        p = pdf.pages[q_start - 1]
                        words = p.extract_words()
                        
                        y0, y1 = None, None
                        
                        # Find bounds for Q.qn
                        for w in words:
                            if w['text'] in (f"Q.{qn}", f"Q.{qn}."):
                                y0 = w['top']
                                break
                                
                        if y0:
                            # Find y1: Stop at first option (A) or next question
                            next_qn = str(int(qn) + 1)
                            for w in words:
                                if w['top'] > y0:
                                    if w['text'] == "(A)":
                                        y1 = w['top']
                                        break
                                    if w['text'] in (f"Q.{next_qn}", f"Q.{next_qn}."):
                                        y1 = w['top']
                                        break
                            if not y1:
                                y1 = p.height - 50
                                
                            # Filter graphics between y0 and y1
                            graphics = p.lines + p.rects + p.curves
                            valid_graphics = []
                            for g in graphics:
                                gw = g.get('width', 0)
                                gh = g.get('height', 0)
                                if gw > 400 and gh > 400: # skip watermarks
                                    continue
                                if g.get('top', 0) >= y0 and g.get('bottom', p.height) <= y1:
                                    valid_graphics.append(g)
                                    
                            if valid_graphics:
                                gx0 = min(g.get('x0', p.width) for g in valid_graphics)
                                gy0 = min(g.get('top', p.height) for g in valid_graphics)
                                gx1 = max(g.get('x1', 0) for g in valid_graphics)
                                gy1 = max(g.get('bottom', 0) for g in valid_graphics)
                                
                                if gx0 < gx1 and gy0 < gy1:
                                    # Add 15px padding
                                    bbox = (
                                        max(0, gx0 - 15), 
                                        max(0, gy0 - 15), 
                                        min(p.width, gx1 + 15), 
                                        min(p.height, gy1 + 15)
                                    )
                                    im = p.crop(bbox).to_image(resolution=200)
                                    img_byte_arr = io.BytesIO()
                                    im.original.save(img_byte_arr, format='PNG')
                                    
                                    q_images[qn] = {
                                        "bytes": img_byte_arr.getvalue(),
                                        "ext": "png",
                                        "width": im.original.width,
                                        "height": im.original.height,
                                        "rect": bbox
                                    }
                except Exception as e:
                    print(f"    [WARN] Vector graphic fallback failed for Q.{qn}: {e}")

    # Second pass: unassigned images on pages with a single question
    for page, figs in page_images.items():
        qnums_on_page = page_qnums.get(page, [])
        if len(qnums_on_page) == 1:
            qn = qnums_on_page[0]
            if qn not in q_images and figs:
                for idx, fig in enumerate(figs):
                    if (page, idx) not in assigned_images:
                        q_images[qn] = fig
                        assigned_images.add((page, idx))
                        break

    return q_images


# ═══════════════════════════════════════════════════════════════════════════════
#  7. MAIN INGESTION
# ═══════════════════════════════════════════════════════════════════════════════

def ingest_pdf_v2(
    pdf_path: str,
    year: int,
    branch: str,
    answer_pdf: str | None = None,
    is_pyq: bool = True,
    dry_run: bool = False,
):
    print(f"\n{'='*65}")
    print(f"  GATE Ingestion v2")
    print(f"  PDF       : {pdf_path}")
    print(f"  Year      : {year}  |  Branch: {branch}")
    print(f"  Mode      : {'PYQ' if is_pyq else 'Non-PYQ (AI solves)'}")
    print(f"  Answer PDF: {answer_pdf or 'N/A'}")
    print(f"  Dry run   : {dry_run}")
    print(f"{'='*65}\n")

    # ── 1. Extract full text ──────────────────────────────────────────────────
    with pdfplumber.open(pdf_path) as pdf:
        total_pages = len(pdf.pages)
    print(f"  Pages: {total_pages}")
    all_text = extract_best_page_text(pdf_path)

    if not all_text.strip():
        print("  ERROR: No text extracted. PDF may be scanned — use ingest_image.py.")
        return

    # ── 2. Parse marks from section headers ───────────────────────────────────
    marks_map = parse_marks_map(all_text)
    one_mk = sum(1 for v in marks_map.values() if v == 1)
    two_mk = sum(1 for v in marks_map.values() if v == 2)
    print(f"  Marks map: {one_mk} × 1-mark  +  {two_mk} × 2-mark  =  {one_mk + two_mk*2} total")

    # ── 3. Load answer key (PYQ only) ─────────────────────────────────────────
    answer_key: dict = {}
    if is_pyq and answer_pdf:
        answer_key = parse_answer_key_pdf(answer_pdf)
    elif is_pyq and not answer_pdf:
        print("  [WARNING] PYQ mode but no --answer-pdf supplied.")
        print("  Pass: --answer-pdf gate_DA2025_answer.pdf")
        print("  Or use --no-pyq for AI-solved mode.")
        return

    # ── 4. Extract embedded images (diagrams) ────────────────────────────────
    print("\n  Extracting embedded images …")
    page_images = extract_images_from_pdf(pdf_path)
    total_imgs = sum(len(v) for v in page_images.values())
    print(f"  Found {total_imgs} diagram(s) across {len(page_images)} page(s)")

    # ── 5. Build page → question-number map ──────────────────────────────────
    page_qnums = build_page_question_map(pdf_path)

    # ── 6. Parse questions from text ─────────────────────────────────────────
    questions = extract_questions_from_text(all_text)
    print(f"\n  Parsed {len(questions)} questions")

    # ── 7. Associate images with questions ───────────────────────────────────
    q_images = associate_images(questions, page_images, page_qnums, pdf_path)
    print(f"  Questions with figures (embedded + fallback snapshots): {len(q_images)}")

    # ── 8. Process each question ─────────────────────────────────────────────
    inserted = failed = skipped = 0

    for q_data in tqdm(questions, desc="Processing"):
        qn = q_data["number"]

        # — Marks —
        marks = marks_map.get(qn, 1)

        # — Answer —
        if is_pyq:
            ans = answer_key.get(qn)
            if not ans:
                print(f"\n  [Q.{qn}] No answer in key — skipping")
                skipped += 1
                continue
            if ans == "MTA":
                print(f"\n  [Q.{qn}] MTA (Marks to All) — skipping")
                skipped += 1
                continue
        else:
            ans = "PENDING"   # AI will fill this later

        # — Determine Structure —
        is_structured = True
        if qn in q_images:
            is_structured = False
        else:
            # Check for complex math symbols, nested matrix brackets, or massive underscore gaps
            import re
            if re.search(r"_{3,}|\[\s*\[|∫|∑|∏", q_data["text"]):
                is_structured = False

        # — Build QuestionIn —
        try:
            q = QuestionIn(
                question_blocks = [make_text_block(q_data["text"])],
                question_type  = q_data["question_type"],
                options        = q_data["options"],
                correct_answer = ans,
                marks          = marks,
                branch_code    = branch,
                is_pyq         = is_pyq,
                pyq_year       = year if is_pyq else None,
                question_number = qn,
                is_structured  = is_structured,
            )
        except Exception as e:
            print(f"\n  [Q.{qn}] Validation error: {e}")
            failed += 1
            continue

        # — AI step —
        if is_pyq:
            q = tag_with_ai(q)              # answer already known → just tag
        else:
            q = solve_and_tag_with_ai(q)    # AI finds answer + tags

        # — Figure upload —
        image_url = None
        if qn in q_images:
            fig = q_images[qn]
            url = upload_question_image(fig, year, branch, qn, dry_run)
            if url:
                image_url = url
                q.add_image_url(url)

        # — Preview —
        print(f"\n  Q.{qn}  [{q.question_type.value}]  {marks}mk  [{q.difficulty.value}]")
        print(f"    Subject : {q.subject_name}")
        print(f"    Topic   : {q.topic_name}")
        print(f"    Answer  : {q.correct_answer}")
        print(f"    Figure  : {image_url or 'None'}")
        # Safe print for Windows console
        safe_text = q.get_plain_text()[:90].encode('ascii', 'replace').decode()
        print(f"    Text    : {safe_text}...")

        if dry_run:
            print("    [DRY RUN] skipped insert")
            inserted += 1
            time.sleep(0.2)
            continue

        # — Insert —
        result = insert_question(q)
        if result:
            inserted += 1
        else:
            failed += 1

        time.sleep(2)   # Groq rate-limit safety

    # Summary
    print(f"\n{'='*65}")
    print(f"  DONE")
    print(f"  Inserted : {inserted}")
    print(f"  Skipped  : {skipped}")
    print(f"  Failed   : {failed}")
    print(f"{'='*65}\n")


# ═══════════════════════════════════════════════════════════════════════════════
#  8. CLI
# ═══════════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="GATE Ingestion v2 — diagrams, math, AI solver",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  PYQ with answer key PDF:
    python ingest_pdf_v2.py --pdf Gate_DA2025.pdf --year 2025 \\
           --answer-pdf gate_DA2025_answerkey.pdf --dry-run

  Non-PYQ (AI finds answers):
    python ingest_pdf_v2.py --pdf practice_set.pdf --year 2025 --no-pyq --dry-run
        """,
    )
    parser.add_argument("--pdf",        required=True,           help="Question paper PDF path")
    parser.add_argument("--year",       required=True, type=int, help="Exam year")
    parser.add_argument("--branch",     default="DA",            help="Branch code (default: DA)")
    parser.add_argument("--answer-pdf", default=None,            help="Answer key PDF (PYQ only)")
    parser.add_argument("--no-pyq",     action="store_true",     help="Non-PYQ mode: AI solves questions")
    parser.add_argument("--dry-run",    action="store_true",     help="Parse & tag, do NOT write to DB")
    args = parser.parse_args()

    ingest_pdf_v2(
        pdf_path   = args.pdf,
        year       = args.year,
        branch     = args.branch,
        answer_pdf = args.answer_pdf,
        is_pyq     = not args.no_pyq,
        dry_run    = args.dry_run,
    )
